### ISSUE TITLE
(0 , prisma_paginate_1.default) is not a function

### ISSUE THREAD

**Issue by masterbater** [sandrewTx08/prisma-paginate#31]
const prisma = new PrismaClient();
const paginate = paginator(prisma);

Just by adding that code it shows error

**Comment by masterbater** [comment]
adding 
`"esModuleInterop": true,`
fixes this thanks. Its not a bug but needs to configure tsconfig.json

**Comment by sandrewTx08** [comment]
Hi @masterbater

Reproducing with both Typescript and Javascript default configuration should not show error.
The issue is related to custom configuration, not the library itself.
I recommend use the tsconfig.json generated by `tsc --init`, it usually needs to adjust few things.
